services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    env_file:
      - ../../.env.base
      - .env
    volumes:
      - ./data:/home/node/.n8n
    networks:
      - traefik_public
      - postgres

networks:
  traefik_public:
    external: true
  postgres:
    external: true
