services:
  homepage-public:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage-public
    volumes:
      - ./config:/app/config 
    environment:
      PUID: ${PUID}
      GUID: ${GUID}
      TZ: ${TZ}

      HOMEPAGE_ALLOWED_HOSTS: www.${DOMAIN},${DOMAIN}
      HOMEPAGE_VAR_JELLYFIN_API_KEY: ${HOMEPAGE_VAR_JELLYFIN_API_KEY}
      HOMEPAGE_VAR_JELLYSEERR_API_KEY: ${HOMEPAGE_VAR_JELLYSEERR_API_KEY}
    networks:
      - traefik_public
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.homepage-public.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
      - "traefik.http.routers.homepage-public.entrypoints=websecure"
      - "traefik.http.routers.homepage-public.tls=true"
      - "traefik.http.routers.homepage-public.tls.certresolver=letsencrypt"
      - "traefik.http.routers.homepage-public.middlewares=security-headers@file"
      
      # Service configuration
      - "traefik.http.services.homepage-public.loadbalancer.server.port=3000"

networks:
  traefik_public:
    external: true
