services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    env_file:
      - ../../.env.base
      - .env
    volumes:
      - ./data:/data
    networks:
      - traefik_admin
      - postgres

networks:
  traefik_admin:
    external: true
  postgres:
    external: true
