admin-base: &admin-base
  entrypoints: [websecure]
  tls:
    certResolver: letsencrypt
  middlewares:
    - security-headers@file

http:
  routers:
    homepage-admin:
      <<: *admin-base
      rule: "Host(`admin.{{ env "DOMAIN" }}`)"
      service: homepage-admin

    homepage-public:
      <<: *admin-base
      rule: "Host(`{{ env "DOMAIN" }}`) || Host(`www.{{ env "DOMAIN" }}`)"
      service: homepage-public

    wiki:
      <<: *admin-base
      rule: "Host(`wiki.{{ env "DOMAIN" }}`)"
      service: wiki
      middlewares:
        - security-headers@file
        - compression@file

    docs-admin:
      <<: *admin-base
      rule: "Host(`docs.{{ env "DOMAIN" }}`)"
      service: docs-admin

    firefly:
      <<: *admin-base
      rule: "Host(`firefly.{{ env "DOMAIN" }}`)"
      service: firefly

    home-assistant:
      <<: *admin-base
      rule: "Host(`ha.{{ env "DOMAIN" }}`)"
      service: home-assistant

  services:
    homepage-admin:
      loadBalancer:
        servers:
          - url: "http://homepage-admin:3000"

    homepage-public:
      loadBalancer:
        servers:
          - url: "http://homepage-public:3000"

    wiki:
      loadBalancer:
        servers:
          - url: "http://docs-wiki-nginx:80"

    docs-admin:
      loadBalancer:
        servers:
          - url: "http://docs-admin-nginx:80"

    firefly:
      loadBalancer:
        servers:
          - url: "http://firefly-core:8080"

    home-assistant:
      loadBalancer:
        servers:
          - url: "http://home-assistant:8123"
