services:
  homepage-public:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage-public
    volumes:
      - ./config:/app/config
    env_file:
      - ../../../.env.base
      - .env
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true
