services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - ../../../.env.base
      - .env
    volumes:
      - ./data:/data/db
      - ./config:/data/configdb
    networks:
      - mongodb
    command:
      - "--auth"
      - "--bind_ip_all"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 512M

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    env_file:
      - ../../../.env.base
      - .env
    networks:
      - mongodb
      - traefik_admin
    depends_on:
      mongodb:
        condition: service_healthy

  mongo-exporter:
    image: percona/mongodb_exporter:0.40
    container_name: mongo-exporter
    restart: unless-stopped
    ports:
      - "9216:9216"
    env_file:
      - ../../../.env.base
      - .env
    networks:
      - mongodb
      - monitoring
    depends_on:
      mongodb:
        condition: service_healthy
    command:
      - '--collect-all'
      - '--compatible-mode'

networks:
  mongodb:
    name: mongodb
    driver: bridge
  traefik_admin:
    external: true
  monitoring:
    external: true
