---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/Shlasky

- Entertainment:
    - Shnetflix:
        - abbr: SH
          href: https://tv.ashlasky.com
