services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://${DOCKHAND_DB_USER}:${DOCKHAND_DB_PASSWORD}@postgres:5432/${DOCKHAND_DB_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
      - /srv:/srv:ro
    networks:
      - traefik_admin
      - postgres

networks:
  traefik_admin:
    external: true
  postgres:
    external: true
