services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    env_file:
      - ../../.env.base
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
      - /srv:/srv:ro
    networks:
      - traefik_admin
      - postgres

networks:
  traefik_admin:
    external: true
  postgres:
    external: true
