services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8082:8082"   # Metrics Endpoint
    env_file:
      - ../../.env.base
      - .env
    volumes:
      # Traefik config files
      - ./traefik.yml:/traefik.yml:ro
      - ./dynamic:/dynamic:ro
      # Certificate storage
      - ./acme/acme.json:/acme.json
      # Docker socket (for service discovery)
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Logs
      - ./logs:/var/log/traefik
    networks:
      - traefik_public
      - traefik_admin

networks:
  traefik_public:
    name: traefik_public
    driver: bridge
  traefik_admin:
    name: traefik_admin
    driver: bridge
