services:
  mc:
    image: itzg/minecraft-server:java21-jdk
    volumes:
    # - ./modpacks:/modpacks:ro
    - ./data:/data
    environment:
      TZ: "Asia/Jerusalem"
      EULA: "true"
      TYPE: "VANILLA"
      MOTD: "Welcome to Shminecraft | Hosted on the Shloud"
      DIFFICULTY: "normal"
      SNOOPER_ENABLED: false
      SERVER_NAME: "Shminecraft"
    ports:
      - "25565:25565"
    restart: always

