services:
  runner:
    image: myoung34/github-runner
    restart: always
    environment:
      # ORG Settings
      - RUNNER_SCOPE=${RUNNER_SCOPE:-org}
      - ORG_NAME=${ORG_NAME}
      # - REPO_NAME="${REPO_NAME}"

      # Runner config
      - RUNNER_NAME_PREFIX=${RUNNER_NAME}
      - RANDOM_RUNNER_SUFFIX=${RANDOM_RUNNER_SUFFIX:-true}
      - RUNNER_WORKDIR=${RUNNER_WORKFIR:-/tmp/runner/work}
      - RUNNER_GROUP=${RUNNER_GROUP:-default}
      - LABELS=${LABELS:-shloud,linux}

      # Auth token
      - ACCESS_TOKEN=${ACCESS_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/tmp/runner
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.3'
          memory: 128M
